export const AUTH_SCREEN = '@AUTH_SCREEN';
export const DAFTARJUAL_SCREEN = '@DAFTARJUAL_SCREEN';
export const FETCH_LOGIN = '@FETCH_LOGIN';
export const LOGOUT = '@LOGOUT';
export const GET_USER_DATA = '@GET_USER_DATA';
export const UPDATE_USER_DATA = '@UPDATE_USER_DATA';
export const GET_PRODUCT_SELLER = '@GET_PRODUCT_SELLER';
export const GET_WISHLIST_SELLER = '@GET_WISHLIST_SELLER';
